first_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('sayhello.urls')),
    path('collatz/', include('collatz.urls')),
    path('tictactoe/', include('tic_tac_toe.urls')),
    path('gradebook/', include('gradebook.urls')),
    path('post/', include('post.urls'))
]

post/urls.py
from django.urls import path
from . import views
app_name = 'post'

urlpatterns = [
    path('', views.register_package, name='register'),
    path('register', views.register_package, name='register'),
    path('login', views.login_view, name='login'),
    path('packages', views.package_list_view, name='list_packages'),
    path('modifypackage/<int:id>', views.modify_package, name='modify'),
    path('package/<int:id>', views.package_detail, name='package_detail'),
    path('logout', views.logout_view, name='logout'),
    
]

post/models.py
from django.db import models
from datetime import date, timedelta
# Create your models here.

def five_days_from_now():
    return date.today() + timedelta(days=5)


class Package (models.Model):
    address = models.CharField(max_length = 1000)
    phone = models.CharField(max_length = 10)
    status = models.CharField(max_length = 50, default='Received')
    eta = models.DateField(default=five_days_from_now)

post/views.py
from django.shortcuts import render, redirect
from .models import Package
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse

# Create your views here.


def register_package(request):
    if request.method == 'GET':
        return render(request, 'post/register_package.html')
    if request.method == 'POST':
        address_ = request.POST.get('address', '')
        phone_ = request.POST.get('phone', '')
        package = Package(address=address_, phone=phone_)
        package.save()
        context = {'success': True, 'id': package.id}
        return render(request, 'post/register_package.html', context)

def login_view(request):
    if request.method == 'POST':
        username_ = request.POST.get('username', '')
        password_ = request.POST.get('password', '')
        user = authenticate(request, username=username_, password=password_)
        if user is not None:
            login(request, user)
            return redirect('post:list_packages')
    return render(request, 'post/login.html')

@permission_required('post.view_package', login_url='post:login')
def package_list_view(request):
    packages = Package.objects.all()
    return render(request, 'post/list_packages.html', {'packages': packages})

@permission_required('post.change_package', login_url='post:login')
def modify_package(request, id):
    package = Package.objects.get(id=id)
    newstatus = request.POST.get('status', package.status)
    neweta = request.POST.get('eta', package.eta)
    package.status = newstatus
    package.eta = neweta
    package.save()
    return redirect('post:list_packages')

def package_detail(request, id):
    package = Package.objects.get(id=id)
    return render(request, 'post/package_detail.html', {'package': package})

def logout_view(request):
    logout(request)
    return redirect('post:login')

post/templates/post/list_packages.html
<!DOCTYPE html>
<html>
    <body>
        <h3>All packages {{nonsense|default:"text"}}</h3>
        <table>
            <th>
                <tr>
                    <td>ID</td>
                    <td>Phone</td>
                    <td>Address</td>
                    <td>Status</td>
                    <td>ETA</td>
                </tr>
            </th>
            {% for package in packages %}
            <tr>
                <td>{{package.id}}</td>
                <td>{{package.phone}}</td>
                <td>{{package.address}}</td>
                <form method="POST" action="{% url 'post:modify' package.id %}">
                    {% csrf_token %}
                    <td><input type="text" name="status" value="{{package.status}}" size="12"></td>
                    <td><input type="date" name="eta" value="{{package.eta|date:"Y-m-d"}}"></td>
                    <td><input type="submit" value="Change status and ETA"></td>
                </form>
            </tr>
            {% endfor %}
        </table>
        <a href="{% url 'post:logout' %}">Logout</a>
    </body>
</html>

post/templates/post/login.html
<!DOCTYPE html>
<html>
    <body>
        <h3>Postman Login</h3>
        <form method="POST" action="{% url 'post:login' %}">
            {% csrf_token %}
            <input name="username" placeholder="username" type="text">
            <input name="password" placeholder="password" type="password">
            <input value="login" type="submit">
        </form>
        <p>Customer? Register a package <a href="{% url 'post:register' %}">here.</a></p>
    </body>
</html>

post/templates/post/package_detail.html
<!DOCTYPE html>
<html>
    <body>
        <h3>Package {{package.id}}</h3>
        <h5>Phone: {{package.phone}}</h5>
        <h5>Address: {{package.address}}</h5>
        <h6>Status: {{package.status}}</h6>
        <h6>ETA: {{package.eta}}</h6>
    </body>
</html>

post/templates/post/register_package.html
<!DOCTYPE html>
<html>
    <body>
        <h3>Register a package</h3>
        <form action="{% url 'post:register' %}" method="POST">
            {% csrf_token %}
            <input type="textarea" placeholder="Address" name="address">
            <input type="text" placeholder="Phone Number" name="phone">
            <input type="submit" value="submit">
        </form>
        {% if success %}
        <p>Success: Registered a package with id {{id}}. Track it
            <a href="{% url 'post:package_detail' id %}">here</a>
        </p>
        {% endif %}
        <p>Already got a tracking id? Check status here:
            <form method="GET" onsubmit="return setAction(this)">
                <input type="text" id="packageid">
                <input type="submit" value="Track">
            </form>
        </p>
        <p>Postmaster? <a href="{% url 'post:login' %}">Login here.</a></p>
        <script>
            function setAction(form) {
                var id = document.getElementById("packageid").value
                var url = "{% url 'post:package_detail' id=1 %}".replace(/1/, id)
                form.action = url
            }    
        </script>
    </body>
</html>