first_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('sayhello.urls')),
    path('collatz/', include('collatz.urls')),
    path('tictactoe/', include('tic_tac_toe.urls')),
    path('gradebook/', include('gradebook.urls')),
    path('post/', include('post.urls'))
]

gradebook/urls.py
from django.urls import path
from . import views

app_name='gradebook'

urlpatterns = [
    path('student/<int:id>', views.student_detail, name='student_detail'),
    path('student/<int:id>/add', views.add_marks, name='add_marks'),
    path('student/<int:id>/delete', views.delete_marks, name='delete_marks'),
    path('login', views.login_to_session, name='login'),
    path('logout', views.logout_, name='logout')
]

post/urls.py
from django.urls import path
from . import views
app_name = 'post'

urlpatterns = [
    path('', views.register_package, name='register'),
    path('register', views.register_package, name='register'),
    path('login', views.login_view, name='login'),
    path('packages', views.package_list_view, name='list_packages'),
    path('modifypackage/<int:id>', views.modify_package, name='modify'),
    path('package/<int:id>', views.package_detail, name='package_detail'),
    path('logout', views.logout_view, name='logout'),
    
]

gradebook/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length = 256)
    #password = models.CharField(default='password', max_length=56)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    def __str__(self):
        return f'{self.name}'

class Marks(models.Model):
    subject_name = models.CharField(max_length = 128)
    score = models.IntegerField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    
    #having a list of Marks inside every student
    #is the same as having a student inside every Mark

    def __str__(self):
        return f'{self.student} - {self.subject_name} - {self.score}'

gradebook/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from .models import Student, Marks
# Create your views here.

@permission_required('gradebook.can_perform_magic', login_url='gradebook:login')
def student_detail(request, id):
    #this is the R of CRUD
    student_ = Student.objects.get(pk=id)
    #SELECT * FROM STUDENT WHERE <INSERT PRIMARY KEY HERE>=id
    marks = Marks.objects.filter(student=student_)
    #SELECT * FROM MARKS WHERE STUDENT=(SELECT * FROM STUDENT
    # WHERE <INSERT PRIMARY KEY HERE>=id)
    #is_authenticated = request.session.get('logged_in_student') == student_.user.username
    context = {'student': student_, 'marks': marks}
    #if is_authenticated:
        #context['authenticated_student_id'] = id
    return render(request, 'gradebook/marksheet.html', context)

def add_marks(request, id):
    #this is the C of CRUD
    student_ = Student.objects.get(pk=id)

    sub_name_ = request.POST.get('sub_name')
    score_ = request.POST.get('score')

    marks = Marks(student=student_, subject_name=sub_name_, score=score_)
    marks.save()
    return redirect('gradebook:student_detail', student_.id)

def delete_marks(request, id):
    #this is the D of crud
    marks = Marks.objects.get(pk=id)
    marks.delete()
    return redirect('gradebook:student_detail', marks.student.id)

def login_to_session(request):
    error_message = ''
    if request.method == 'POST':
        username_ = request.POST.get('username')
        password_ = request.POST.get('password')
        user = authenticate(username=username_, password=password_)
        if user is not None:
            login(request, user)
            student = Student.objects.get(user=user)
            return redirect('gradebook:student_detail', student.id)
        else:
            error_message = 'Wrong password'
    context = {'error_message': error_message}
    return render(request, 'gradebook/login.html', context)

def logout_(request):
    logout(request)
    return redirect('gradebook:login')

gradebook/templates/gradebook/login.html
<!DOCTYPE html>
<html>
    <body>
        <form method="POST" action="{% url 'gradebook:login' %}">
            {% csrf_token %}
            <p>{{error_message}}</p>
            <label for="username">Username</label>
            <input type="text" name="username" id="username"><br/>
            <label for="password">Password</label>
            <input type="password" name="password" id="password"><br/>
            <input type="submit" value="Login">
        </form>
    </body>
</html>

gradebook/templates/gradebook/marksheet.html
<!DOCTYPE html>
<html>
    <body>
    <h3>{{student.name}}</h3>
        <p>Authenticated User: {{user}}, {{user.is_authenticated}}</p>
        <table>
            {% for item in marks %}
            <tr>
                <td>{{item.subject_name}}</td>
                <td>{{item.score}}</td>
                <form method="DELETE" action="{% url 'gradebook:delete_marks' item.id%}">
                    <td><input type="submit" value="delete"></td>
                </form>
            </tr>
            {% endfor %}
            <form method="POST" action="{% url 'gradebook:add_marks' student.id %}">
                {% csrf_token %}
                <tr>
                    <td><input type="text" name="sub_name"></td>
                    <td><input type="text" name="score"></td>
                    <td><input type="submit" value="add"></td>
                </tr>
            </form>
        </table>
    <a href="{% url 'gradebook:logout' %}">Logout</a>
    </body>
</html>